# Generated by Django 4.2.7 on 2025-08-09 06:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('crop_type', models.CharField(choices=[('rice', 'Rice'), ('jute', 'Jute')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_detected', models.BooleanField()),
                ('disease_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('severity', models.CharField(max_length=50)),
                ('bacterial_infection', models.BooleanField(default=False)),
                ('recommendations', models.JSONField(default=list)),
                ('prevention_strategies', models.JSONField(default=list)),
                ('danger_level', models.TextField(blank=True)),
                ('economic_impact', models.TextField(blank=True)),
                ('treatment_timeline', models.TextField(blank=True)),
                ('monitoring_advice', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='analysis.cropimage')),
            ],
        ),
    ]
