# Generated by Django 4.2.7 on 2025-08-21 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_evaluationresult'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='analysisresult',
            table='analysis_data',
        ),
    ]
